import unittest
import os
import tempfile
from pikpak_llc.llc_parser import parse_llc, parse_llc_project

class TestLLCParser(unittest.TestCase):
    def setUp(self):
        self.fixture_path = "tests/fixtures/losslesscut-3.69-real.llc"
        
    def test_parse_real_llc_file(self):
        """
        Verify that the parser can correctly read the real JSON5 
        .llc file generated by LosslessCut v3.69.0.
        """
        segments = parse_llc(self.fixture_path)
        
        self.assertEqual(len(segments), 4)
        
        # Verify all four segments exactly as requested by BROWSER REVIEW LEAD
        # Seg 1: 399.453776 -> 559.480152
        self.assertAlmostEqual(segments[0]["start"], 399.453776, places=5)
        self.assertAlmostEqual(segments[0]["end"], 559.480152, places=5)
        
        # Seg 2: 579.143852 -> 700.285526
        self.assertAlmostEqual(segments[1]["start"], 579.143852, places=5)
        self.assertAlmostEqual(segments[1]["end"], 700.285526, places=5)
        
        # Seg 3: 720.604865 -> 948.453050
        self.assertAlmostEqual(segments[2]["start"], 720.604865, places=5)
        self.assertAlmostEqual(segments[2]["end"], 948.453050, places=5)
        
        # Seg 4: 1003.248263 -> 1045.356133
        self.assertAlmostEqual(segments[3]["start"], 1003.248263, places=5)
        self.assertAlmostEqual(segments[3]["end"], 1045.356133, places=5)

    def test_project_preserves_media_filename_for_source_matching(self):
        project = parse_llc_project(self.fixture_path)

        self.assertEqual(project["mediaFileName"], "proxy1_h264.mp4")
        self.assertEqual(project["cutSegments"], parse_llc(self.fixture_path))

    def test_missing_cut_segments(self):
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix=".llc") as tf:
            tf.write("{version: 2, mediaFileName: 'test.mp4'}")
            tf_name = tf.name
        
        try:
            with self.assertRaises(ValueError) as ctx:
                parse_llc(tf_name)
            self.assertIn("Missing 'cutSegments'", str(ctx.exception))
        finally:
            os.remove(tf_name)

    def test_malformed_json5(self):
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix=".llc") as tf:
            tf.write("{version: 2, cutSegments: [{start: 1") # Unclosed
            tf_name = tf.name
            
        try:
            with self.assertRaises(ValueError) as ctx:
                parse_llc(tf_name)
            self.assertIn("Failed to parse LLC JSON5", str(ctx.exception))
        finally:
            os.remove(tf_name)

    def test_missing_start_end(self):
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix=".llc") as tf:
            tf.write("{version: 2, cutSegments: [{start: 1}, {end: 2}]}")
            tf_name = tf.name
            
        try:
            segs = parse_llc(tf_name)
            self.assertEqual(len(segs), 0) # Segments without both start and end are ignored
        finally:
            os.remove(tf_name)

    def test_invalid_timestamps(self):
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix=".llc") as tf:
            tf.write("{version: 2, cutSegments: [{start: 'abc', end: 'def'}]}")
            tf_name = tf.name
            
        try:
            with self.assertRaises(ValueError):
                parse_llc(tf_name) # float('abc') raises ValueError
        finally:
            os.remove(tf_name)
            
    def test_end_not_greater_than_start(self):
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix=".llc") as tf:
            tf.write("{version: 2, cutSegments: [{start: 10, end: 5}]}")
            tf_name = tf.name
            
        try:
            with self.assertRaises(ValueError) as ctx:
                parse_llc(tf_name)
            self.assertIn("end (5.0) is not greater than start (10.0)", str(ctx.exception))
        finally:
            os.remove(tf_name)

if __name__ == '__main__':
    unittest.main()
